# Logging Configuration
logging:
  version: 1
  formatters:
    simpleFormatter:
      format: "%(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    consoleHandler:
      class: logging.StreamHandler
      formatter: simpleFormatter
      stream: ext://sys.stdout
    fileHandler:
      class: logging.handlers.TimedRotatingFileHandler
      formatter: simpleFormatter
      filename: logs/twilio_system_logs.log
      when: midnight # Rotate the log file every midnight
      interval: 1 # Interval is 1 day
      backupCount: 30 # Optional: Set this to keep 30 days of logs, older logs are deleted.
  root:
    level: INFO
    handlers: [fileHandler]

# Voice AI App Credentials
voice_ai_app:
  username: !Parse ["os.environ.get('CCAAS_USERNAME')"]
  password: !Parse ["os.environ.get('CCAAS_PASSWORD')"]

# Twilio Configuration
twilio:
  auth_token: !Parse ["os.environ.get('TWILIO_AUTH_TOKEN')"]

voices:
  internal_error_voice_play_url: https://{twilio function url}/assets/Internal_Error_occured.mp3
